#pragma once

static const char SMARTSCORE_PROVISIONING_PAGE[] =
"<!doctype html><html lang='zh-CN'><head><meta charset='utf-8'>"
"<meta name='viewport' content='width=device-width,initial-scale=1'>"
"<title>SmartScore 配网</title><style>"
"body{margin:0;background:#f5f7fb;color:#17202a;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif}"
"main{max-width:460px;margin:auto;padding:24px 18px}section{background:white;padding:18px;border-radius:14px;box-shadow:0 4px 18px #18202a18}"
"h1{font-size:25px;margin:0 0 8px}p{color:#667085;line-height:1.6}label{display:block;font-weight:600;margin:14px 0 6px}"
"input,select,button{box-sizing:border-box;width:100%;height:44px;border-radius:9px;font-size:16px}"
"input,select{border:1px solid #ccd3dc;padding:0 10px;background:white}button{border:0;background:#1667ff;color:white;font-weight:600;margin-top:14px}"
"button.secondary{background:#eef3ff;color:#1555cc}pre{white-space:pre-wrap;background:#f7f8fa;padding:12px;border-radius:9px;min-height:52px}"
"</style></head><body><main><section><h1>SmartScore 配网</h1>"
"<p>备用网页配网。BLE 仍是本阶段主要测试路径。</p>"
"<button class='secondary' onclick='scan()'>扫描附近 Wi-Fi</button>"
"<label>Wi-Fi 名称</label><select id='networks' onchange=\"ssid.value=this.value\"><option value=''>请选择或手动输入</option></select>"
"<input id='ssid' maxlength='32' placeholder='SSID'>"
"<label>Wi-Fi 密码</label><input id='password' type='password' maxlength='64' placeholder='开放网络可留空'>"
"<button onclick='connect()'>连接 Wi-Fi</button><button class='secondary' onclick='resetWifi()'>清除配置</button>"
"<pre id='status'>等待操作</pre></section></main><script>"
"const out=document.getElementById('status');"
"async function scan(){out.textContent='扫描中…';try{const r=await fetch('/api/wifi/scan');const d=await r.json();"
"const s=document.getElementById('networks');s.innerHTML='<option value=\"\">请选择或手动输入</option>';"
"(d.networks||[]).forEach(n=>{const o=document.createElement('option');o.value=n.ssid;o.textContent=n.ssid+' ('+n.rssi+' dBm)';s.appendChild(o)});out.textContent='扫描完成'}catch(e){out.textContent='扫描失败：'+e}}"
"async function connect(){const body=new URLSearchParams({ssid:document.getElementById('ssid').value,password:document.getElementById('password').value});"
"out.textContent='连接中…';try{const r=await fetch('/connect',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});out.textContent=await r.text()}catch(e){out.textContent='提交失败：'+e}}"
"async function resetWifi(){try{const r=await fetch('/reset');out.textContent=await r.text()}catch(e){out.textContent='清除失败：'+e}}"
"async function poll(){try{const r=await fetch('/api/status',{cache:'no-store'});const d=await r.json();out.textContent=JSON.stringify(d,null,2)}catch(e){}setTimeout(poll,1500)}poll();"
"</script></body></html>";
