/*
 * SPDX-FileCopyrightText: 2025-2026 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * DO NOT MODIFY THIS FILE.
 *
 * tools/check_fw_versions.py generated this file.
 *
 * This file is autogenerated by a pre-commit hook.
 * Version info here is populated from idf_component.yml
 */
#ifndef __ESP_HOSTED_COPROCESSOR_FW_VER_H__
#define __ESP_HOSTED_COPROCESSOR_FW_VER_H__

#define PROJECT_VERSION_MAJOR_1 2
#define PROJECT_VERSION_MINOR_1 12
#define PROJECT_VERSION_PATCH_1 6

/**
 * Macro to convert version number into an integer
 */
#define ESP_HOSTED_VERSION_VAL(major, minor, patch) ((major << 16) | (minor << 8) | (patch))

#endif
