idf_component_register(
    SRCS
        "src/screen_adapter.c"
        "src/screen_modes.c"
    INCLUDE_DIRS "include"
    REQUIRES
        app_font
        audio_s3_adapter
        common
        display_board_adapter
        esp_hw_support
        heap
        input_source_manager
        json
        music_display
        practice_advice_view
        score_data
        score_player
        scoring_service
        s3_bus
        screen_legacy_storage
        screen_score_bridge
        speaker_service
        ui_app
        ui_generated
        usb_midi
        esp_timer
)
